### ISSUE TITLE
Tamil: "isolated" form of U+0BC2 is different from the Unicode code charts

### ISSUE THREAD

**Issue by emuller-amazon** [notofonts/tamil#1]
The "isolated" form of U+0BC2 (e.g. when applied to a U+25CC i.e. the glyph cmaped from U+0BC2) is different from what is shown in the Unicode code charts.

I do understand that Tamils learn they script as a syllabary, and therefore that the "isolated" form of vowel signs is rarely seen in practice.

**Comment by simoncozens** [comment]
I'm going to say that while this *is* different from the Unicode code charts, as Jelle argues, that's not necessarily wrong. Fonts aren't code charts. And it's internally consistent, so I don't see a problem here.

**Comment by jamadagni** [comment]
With the basic Tamil 18 consonants the VS-U/VS-UU will get ligated so the internal glyphs assigned to the respective code points will never get displayed. With additional consonants ஜ ஶ ஷ ஸ ஹ க்ஷ mostly used for words of non-Tamil-language origin, the internal glyphs do get display as these do not ligate in current orthography.

The glyphs show in the chart show one contextual form of the VS-U/VS-UU used as part of ligatures with some of the basic Tamil consonants ங ப ய வ as in ஙு ஙூ பு பூ யு யூ வு வூ. So it is just about perception.

The font may not be able to provide the contextual forms of the vowel signs in isolation (one can't expect separate characters for all the contextual forms anyhow) but it is able to display valid normal Tamil text correctly.
