### ISSUE TITLE
Noto Sans Tamil UI baseline alignment issue in the Android 13 environment

### ISSUE THREAD

**Issue by chrissimpkins** [notofonts/tamil#13]
In Android 13, the text rendering for Tamil is broken in several apps (Settings, Gboard, Google Keep, Google Translate, Reddit, Spotify, etc.). The issue is that some letters are rendered slightly higher than others, making it seem like it wasn't written straight. A word which exhibits this is அளிக்கப்பட்ட. The letters க் and க, ப் and ப, and ட் and ட all should render with the same baseline, but they do not. Instead, letters with the dot on top (combining character: U+0BCD TAMIL SIGN VIRAMA) are rendered slightly higher than the letters without.

We can confirm this with the Noto Sans Tamil UI v2.001 build in an Android 13 test environment.

![1664455782](https://user-images.githubusercontent.com/4249591/193059209-052f937a-a4fd-474c-801d-536b8d87fa64.png)

I cannot reproduce it with the unhinted Noto Sans Tamil v2.003 VF build (note: non-UI build, not the UI build used in the bug report above) found in the release  https://github.com/notofonts/tamil/releases/tag/NotoSansTamil-v2.003

<img width="1966" alt="B23nk266TzaAvom" src="https://user-images.githubusercontent.com/4249591/193060563-df796d64-b0f5-4999-bb52-0381b6f1232a.png">

**Comment by simoncozens** [comment]
This turns out to be a bug in the (rather hacky) `make-ui-vf.py` script which generated variable UI fonts from variable non-UI fonts; it applied a translation transformation to all glyphs - including component glyphs, whose components already had the same translation applied to them, so they were being translated twice.

**Comment by chrissimpkins** [comment]
Thanks Simon.  The fixed file was pushed to Android Text eng.  Awaiting confirmation of the fix.

**Comment by simoncozens** [comment]
Are we still waiting?

**Comment by chrissimpkins** [comment]
Sorry, this was confirmed.  Thanks Simon

**Comment by simoncozens** [comment]
The version of UI font included in [this release](https://github.com/notofonts/tamil/releases/tag/NotoSansTamil-v2.004) has the fix.
