### ISSUE TITLE
Kerning exceptions apply incorrectly, causing clashes (workaround required)

### ISSUE THREAD

**Issue by Hoolean** [notofonts/tamil#15]
Hello!

When testing ufo2ft across the Noto Fonts project we identified [ufo2ft#706](https://github.com/googlefonts/ufo2ft/issues/706), which causes base-base kerning exceptions to apply incorrectly to kerning pairs that use groups containing marks.

We are making some noise here in case you wish to fix the issue in any releases you make before the bug is resolved upstream.

### e.g. in sources

> $ [kerning-validator](https://github.com/daltonmaag/kerning-validator/tree/b2aafc7) [NotoSerifTamil-BoldItalic.ufo](https://github.com/notofonts/tamil/tree/1beb9bc/sources/NotoSerifTamil-BoldItalic.ufo)

```
script='Taml' direction='LTR': aa-tamil ha-tamil should be -60 but is -160
script='Taml' direction='LTR': aa-tamil lu-tamil should be -50 but is -150
script='Taml' direction='LTR': aa-tamil luu-tamil should be -50 but is -150
script='Taml' direction='LTR': aa-tamil nnnu-tamil should be -50 but is -150
script='Taml' direction='LTR': aa-tamil nnu-tamil should be -50 but is -150
script='Taml' direction='LTR': aa-tamil nnuu-tamil should be -50 but is -150
script='Taml' direction='LTR': cuu-tamil ha-tamil should be -60 but is -160
script='Taml' direction='LTR': cuu-tamil lu-tamil should be -50 but is -150
script='Taml' direction='LTR': cuu-tamil luu-tamil should be -50 but is -150
script='Taml' direction='LTR': cuu-tamil nnnu-tamil should be -50 but is -150
script='Taml' direction='LTR': cuu-tamil nnu-tamil should be -50 but is -150
script='Taml' direction='LTR': cuu-tamil nnuu-tamil should be -50 but is -150
script='Taml' direction='LTR': nguu-tamil ha-tamil should be -60 but is -160
script='Taml' direction='LTR': nguu-tamil lu-tamil should be -50 but is -150
script='Taml' direction='LTR': nguu-tamil luu-tamil should be -50 but is -150
script='Taml' direction='LTR': nguu-tamil nnnu-tamil should be -50 but is -150
script='Taml' direction='LTR': nguu-tamil nnu-tamil should be -50 but is -150
script='Taml' direction='LTR': nguu-tamil nnuu-tamil should be -50 but is -150
script='Taml' direction='LTR': onethousand-tamil ha-tamil should be -60 but is -160
script='Taml' direction='LTR': onethousand-tamil lu-tamil should be -50 but is -150
script='Taml' direction='LTR': onethousand-tamil luu-tamil should be -50 but is -150
script='Taml' direction='LTR': onethousand-tamil nnnu-tamil should be -50 but is -150
script='Taml' direction='LTR': onethousand-tamil nnu-tamil should be -50 but is -150
script='Taml' direction='LTR': onethousand-tamil nnuu-tamil should be -50 but is -150
script='Taml' direction='LTR': puu-tamil ha-tamil should be -60 but is -160
script='Taml' direction='LTR': puu-tamil lu-tamil should be -50 but is -150
script='Taml' direction='LTR': puu-tamil luu-tamil should be -50 but is -150
script='Taml' direction='LTR': puu-tamil nnnu-tamil should be -50 but is -150
script='Taml' direction='LTR': puu-tamil nnu-tamil should be -50 but is -150
script='Taml' direction='LTR': puu-tamil nnuu-tamil should be -50 but is -150
script='Taml' direction='LTR': vuu-tamil ha-tamil should be -60 but is -160
script='Taml' direction='LTR': vuu-tamil lu-tamil should be -50 but is -150
script='Taml' direction='LTR': vuu-tamil luu-tamil should be -50 but is -150
script='Taml' direction='LTR': vuu-tamil nnnu-tamil should be -50 but is -150
script='Taml' direction='LTR': vuu-tamil nnu-tamil should be -50 but is -150
script='Taml' direction='LTR': vuu-tamil nnuu-tamil should be -50 but is -150
script='Taml' direction='LTR': yuu-tamil ha-tamil should be -60 but is -160
script='Taml' direction='LTR': yuu-tamil lu-tamil should be -50 but is -150
script='Taml' direction='LTR': yuu-tamil luu-tamil should be -50 but is -150
script='Taml' direction='LTR': yuu-tamil nnnu-tamil should be -50 but is -150
script='Taml' direction='LTR': yuu-tamil nnu-tamil should be -50 but is -150
script='Taml' direction='LTR': yuu-tamil nnuu-tamil should be -50 but is -150
```

Note: this is a partial list; the affected pairs vary by UFO, which has been omitted for brevity.

### e.g. in production fonts

Example pair: ௲லு [should be kerned](https://github.com/notofonts/tamil/blob/main/sources/NotoSerifTamil-Regular.ufo/kerning.plist#L113-L116) in googlefonts/ttf/NotoSerifTamil-Regular.ttf from [the latest release](https://github.com/notofonts/tamil/releases/tag/NotoSerifTamil-v2.003) but is not.

## Workaround

1. Run [kerning-validator](https://github.com/daltonmaag/kerning-validator/tree/b2aafc7) on each source UFO, as shown in the example above
2. If issues are reported, split the affected groups into one containing only bases and one containing only marks to resolve

**Comment by Hoolean** [comment]
Found a more severe production example; this issue causes ஆலூ to clash in Noto Serif Black Italic:
![ஆலூ shown clashing in the Google Fonts type tester](https://user-images.githubusercontent.com/2150762/218708178-463f1268-62f4-4fc2-9dcc-06123913eb49.png)

**Comment by simoncozens** [comment]
Thank you, that's helpful! When I try this with the new kern writer in ufo2ft, I hit https://github.com/googlefonts/ufo2ft/issues/702, so there are clearly some assumptions we are making about base/base base/mark kerning that are incorrect.

**Comment by Hoolean** [comment]
Indeedy, kerning-validator won't be happy testing with ufo2ft's `main` until googlefonts/ufo2ft#705 is merged, although taking a peek we found that the bug has been wily enough to survive the refactor for script-based splitting 👹

We are going to have to introduce an additional split on pairs to break them into statements that only match contexts with no marks (for the base lookup) and that only match contexts with at least one mark (for the marks lookup), which should resolve this and a few other corner cases, and is the automatic equivalent of the current manual workaround : )

**Comment by simoncozens** [comment]
OK, so if I build with ufo2ft@a8c489d, it builds but kerning doesn't work. But joyously, ufo2ft@29b7ca5 fixes kerning:
![shape](https://user-images.githubusercontent.com/106728/225873074-f45c9a3e-e257-4965-ba35-40e9bb39f47e.png)
