### ISSUE TITLE
NotoSerifTamilSlanted-VF.ttf and NotoSerifTamilSlanted-Italic-VF.ttf in tree/main/unhinted/variable-ttf

### ISSUE THREAD

**Issue by twardoch** [notofonts/tamil#4]
In tree/main/unhinted/variable-ttf we have both NotoSerifTamilSlanted-VF.ttf and NotoSerifTamilSlanted-Italic-VF.ttf. I think one of them should be removed? (Also in slim-variable-ttf )

**Comment by simoncozens** [comment]
No longer the case!
