### ISSUE TITLE
Noto Serif Tamil Slanted is named “NotoSerifTamilSlanted”

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tamil#6]
### Font
NotoSerifTamilSlanted-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/07db6d0d84682ffe11e14da4a9cbabdaaf2e909b/unhinted/otf/NotoSerifTamilSlanted/NotoSerifTamilSlanted-Regular.otf
Date: 2022-03-21

### Font version
Version 2.001

### Issue
The font family name (name ID 1) for Noto Serif Tamil Slanted is “NotoSerifTamilSlanted”. It should be “Noto Serif Tamil Slanted”. No other Noto fonts omit spaces from their font family names.

**Comment by simoncozens** [comment]
I'm not 100% sure what's going on with this family but I *think* we've renamed it from "Slanted" to "Italic" and made it part of the Serif family.
